export interface Treatment {
  treatmentId: number;
  therapistId: number;
  childId: number;
  treatmentDate: string;
  startTime: string;
  endTime: string;
  words: string;
  sentence: string;
  conversation: string;
}

export const treatmentDummyData: Treatment[] = [
  {
    treatmentId: 1,
    therapistId: 1,
    childId: 1,
    treatmentDate: '2025-01-23',
    startTime: '13:00:00',
    endTime: '13:30:00',
    words: '사과, 바나나, 오렌지',
    sentence: '나는 사과를 좋아해요.',
    conversation: '오늘 뭐 먹었어요?',
  },
  {
    treatmentId: 2,
    therapistId: 1,
    childId: 2,
    treatmentDate: '2025-01-24',
    startTime: '14:00:00',
    endTime: '14:30:00',
    words: '책, 연필, 지우개',
    sentence: '책은 지식을 줘요.',
    conversation: '오늘 학교에서 뭐 배웠어요?',
  },
  {
    treatmentId: 3,
    therapistId: 1,
    childId: 3,
    treatmentDate: '2025-01-25',
    startTime: '15:00:00',
    endTime: '15:30:00',
    words: '강아지, 고양이, 토끼',
    sentence: '강아지가 귀여워요.',
    conversation: '반려동물을 키워본 적 있어요?',
  },
  {
    treatmentId: 4,
    therapistId: 1,
    childId: 1,
    treatmentDate: '2025-01-26',
    startTime: '13:00:00',
    endTime: '13:30:00',
    words: '우유, 주스, 물',
    sentence: '나는 우유를 마셔요.',
    conversation: '좋아하는 음료가 뭐예요?',
  },
  {
    treatmentId: 5,
    therapistId: 1,
    childId: 2,
    treatmentDate: '2025-01-27',
    startTime: '14:00:00',
    endTime: '14:30:00',
    words: '자동차, 자전거, 버스',
    sentence: '버스로 학교에 가요.',
    conversation: '어떻게 학교에 가요?',
  },
  {
    treatmentId: 6,
    therapistId: 1,
    childId: 3,
    treatmentDate: '2025-01-28',
    startTime: '15:00:00',
    endTime: '15:30:00',
    words: '빨강, 파랑, 노랑',
    sentence: '노란색이 예뻐요.',
    conversation: '좋아하는 색깔은 뭐예요?',
  },
  {
    treatmentId: 7,
    therapistId: 1,
    childId: 1,
    treatmentDate: '2025-01-29',
    startTime: '13:00:00',
    endTime: '13:30:00',
    words: '의자, 책상, 소파',
    sentence: '의자에 앉아요.',
    conversation: '오늘 어디에 앉았어요?',
  },
  {
    treatmentId: 8,
    therapistId: 1,
    childId: 2,
    treatmentDate: '2025-01-30',
    startTime: '14:00:00',
    endTime: '14:30:00',
    words: '바다, 산, 강',
    sentence: '산은 높아요.',
    conversation: '여행 가고 싶은 곳이 어디예요?',
  },
  {
    treatmentId: 9,
    therapistId: 1,
    childId: 3,
    treatmentDate: '2025-01-31',
    startTime: '15:00:00',
    endTime: '15:30:00',
    words: '사과, 배, 포도',
    sentence: '포도가 달아요.',
    conversation: '과일 중에서 뭐가 좋아요?',
  },
  {
    treatmentId: 10,
    therapistId: 1,
    childId: 1,
    treatmentDate: '2025-02-01',
    startTime: '13:00:00',
    endTime: '13:30:00',
    words: '공, 인형, 블록',
    sentence: '블록 쌓기가 재밌어요.',
    conversation: '무엇으로 놀고 싶어요?',
  },
  {
    treatmentId: 1,
    therapistId: 1,
    childId: 1,
    treatmentDate: '2024-12-02',
    startTime: '10:00:00',
    endTime: '11:00:00',
    words: '언어 치료',
    sentence: '나는 사과를 좋아해요.',
    conversation: '오늘 뭐 먹었어요?',
  },
  {
    treatmentId: 2,
    therapistId: 1,
    childId: 2,
    treatmentDate: '2024-12-02',
    startTime: '13:00:00',
    endTime: '14:00:00',
    words: '발음 교정',
    sentence: '책은 지식을 줘요.',
    conversation: '오늘 학교에서 뭐 배웠어요?',
  },
  {
    treatmentId: 3,
    therapistId: 1,
    childId: 3,
    treatmentDate: '2024-12-02',
    startTime: '15:00:00',
    endTime: '16:00:00',
    words: '청각 훈련',
    sentence: '강아지가 귀여워요.',
    conversation: '반려동물을 키워본 적 있어요?',
  },
];
